services:
  db:
    image: mongo:latest
    container_name: mongo_container
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  app:
    build: .
    container_name: api
    depends_on:
      - db
    env_file:
      - .env
    volumes:
      - .:/app
    ports:
     - "8000:8000"
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
  
volumes:
  mongo_data: